# Generated by Django 3.2.7 on 2021-09-17 15:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('checklist', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='checklist',
            old_name='category',
            new_name='status',
        ),
    ]
