# Generated by Django 3.2.7 on 2021-10-04 19:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('blogs', '0005_auto_20211004_1056'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='name',
            field=models.ForeignKey(default='Anonymous', on_delete=django.db.models.deletion.CASCADE, related_name='user', to=settings.AUTH_USER_MODEL),
        ),
    ]
